language: python

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - graphviz
      - libgraphviz-dev
      - pkg-config

install:
  - pip install --upgrade pip setuptools tox virtualenv coveralls
  - npm install -g bower

env:
  - TOXENV=isort
  - TOXENV=flake8
  - TOXENV=py35-django111
  - TOXENV=py35-django220
  - TOXENV=py35-django_trunk

script:
  - tox

notifications:
  email: false

matrix:
  allow_failures:
    - env: TOXENV=py35-django_trunk

after_success: coveralls
