language: python

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - python3.5-dev

install:
  - pip install --upgrade pip setuptools tox virtualenv coveralls
  - npm install -g bower
  - apt install -y graphviz libgraphviz-dev pkg-config

env:
  - TOXENV=isort
  - TOXENV=flake8
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django110
  - TOXENV=py34-django111
  - TOXENV=py34-django_trunk
  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=py35-django110
  - TOXENV=py35-django111
  - TOXENV=py35-django_trunk

script:
  - tox

notifications:
  email: false

matrix:
  allow_failures:
    - env: TOXENV=py34-django_trunk
    - env: TOXENV=py35-django_trunk